---
version: 1

ansible_config: ansible.cfg

dependencies:
  galaxy: collections/requirements.yaml
  python: requirements.txt

additional_build_steps:
  prepend: |
    RUN pip3 install --upgrade pip setuptools
  append:
    - RUN ls -al /
