---
- name: PLAY 1 - PWD
  hosts: localhost
  tasks:

    - name: Run 'pwd' on linux
      ansible.builtin.shell:
        cmd: pwd
      register: result  

    - name: TASK 1 - Print Working Directory
      ansible.builtin.debug:
        msg: "{{ result }}"