# This playbook is built to CHECK, not configure the devices.
# Variables required:
#   - local_usernmae
---
- name: 1.1 - Management Plane
  hosts: switches
  tasks:

    - name: 0.0.0 - Get Running config
      cisco.ios.ios_command:
        commands:
          - show running-config all
      register: runningconfig

    - name: 1.1.1 - aaa new-model
      cisco.ios.ios_config:
        lines:
          - aaa new-model

    - name: 1.1.2 - aaa authentication login
      cisco.ios.ios_config:
        lines:
          - aaa authentication login default group ISE-TACACS-GROUP local
      when: '"aaa group server tacacs+ ISE-TACACS-GROUP" in runningconfig.stdout[0]'

    - name: 1.1.3 - aaa authentication enable default
      cisco.ios.ios_config:
        lines:
          - aaa authentication enable default enable

      # Make sure no login method is explicitly set on VTY - should be using the default method list
    - name: 1.1.4 - login authentication
      cisco.ios.ios_config:
        lines:
          - no login authentication
        parents:
          - line vty 0 4
      when: '"line vty 0 4\n login authentication" in runningconfig.stdout[0]'

    - name: 1.1.5 - http authentication
      cisco.ios.ios_config:
        lines:
          - ip http authentication local
      when: '"ip http secure-server" in runningconfig.stdout[0]'

    - name: 1.1.6 - aaa accounting
      cisco.ios.ios_config:
        lines:
          - aaa accounting commands 15 default start-stop group ISE-TACACS-GROUP

    - name: 1.1.7 - aaa accounting connection
      cisco.ios.ios_config:
        lines:
          - aaa accounting connection default start-stop group ISE-TACACS-GROUP

    - name: 1.1.8 - aaa accounting exec
      cisco.ios.ios_config:
        lines:
          - aaa accounting exec default start-stop group ISE-TACACS-GROUP

    - name: 1.1.9 - aaa accounting network
      cisco.ios.ios_config:
        lines:
          - aaa accounting network default start-stop group ISE-TACACS-GROUP

    - name: 1.1.10 - aaa accounting system
      cisco.ios.ios_config:
        lines:
          - aaa accounting system default start-stop group ISE-TACACS-GROUP

- name: 1.2 - Access Rules
  hosts: switches
  tasks:

    - name: 1.2.1 - privilige 1 for local users
      cisco.ios.ios_config:
        lines:
          - username {{ local_username }} privilege 1
      when: '("username " + local_username +  " privilege") in runningconfig.stdout[0]'

    - name: 1.2.2 - transport input ssh
      cisco.ios.ios_config:
        lines:
          - transport input ssh
        parents:
          - line vty 0 4

    - name: 1.2.3 - no exec for aux0 lines
      cisco.ios.ios_config:
        lines:
          - no exec
        parents:
          - line aux 0  
      when: '"line aux" in runningconfig.stdout[0]'

    - name: 1.2.4 - ACL for VTY Existance
      cisco.ios.ios_config:
        lines:
          - ip access-list extended ACL-VTY-PERMIT

    - name: 1.2.5 - ACL for VTY Application
      cisco.ios.ios_config:
        lines:
          - ip access-group ACL-VTY-PERMIT in
        parents:
          - line vty 0 4
  
    - name: 1.2.6 - exec timeout for AUX line
      cisco.ios.ios_config:
        lines:
          - exec-timeout 10
        parents:
          - line aux 0  
      when: '"line aux" in runningconfig.stdout[0]'

    - name: 1.2.7 - exec timeout for CONSOLE line
      cisco.ios.ios_config:
        lines:
          - exec-timeout 10
        parents:
          - line con 0

    - name: 1.2.8 - exec timeout for VTY line
      cisco.ios.ios_config:
        lines:
          - exec-timeout 10
        parents:
          - line vty 0 4

    - name: 1.2.9 - transport input none for AUX line
      cisco.ios.ios_config:
        lines:
          - transport input none
        parents:
          - line aux 0  
      when: '"line aux" in runningconfig.stdout[0]'

    - name: 1.2.10 - http secure server limit
      cisco.ios.ios_config:
        lines:
          - ip http max-connections 5
      when: '"ip http secure-server" in runningconfig.stdout[0]'

    - name: 1.2.11 - exec timeout for http
      cisco.ios.ios_config:
        lines:
          - ip http timeout-policy idle 600 life 43200 requests 43200
      when: '"ip http secure-server" or "server" in runningconfig.stdout[0]'