---
- name: PLAY 1 - SHOW VERSION
  hosts: localhost
  tasks:

    - name: TASK 1 - Run 'show version'
      ansible.builtin.debug:
        commands:
          - "sh ver | i XE Software,"
      register: ver

    - name: TASK 2 - Display 'show version'
      ansible.builtin.debug:
        msg: "{{ ver }}"